ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(20) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255) DEFAULT '';
ALTER TABLE scrim_requests ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255) DEFAULT '';
